import { generateMasterKey } from '../server/crypto.js'

async function main() {
  const args = process.argv.slice(2)
  const cmd = args[0]

  if (cmd === 'keys' && args[1] === 'generate') {
    console.log(generateMasterKey())
    return
  }

  if (cmd === 'init') {
    console.log(`import { defineSchema } from 'gd-db/server'
export default defineSchema({
  tables: {
    users: { columns: {
      id: { type: 'uuid', primaryKey: true },
      name: { type: 'text' },
      created_at: { type: 'timestamptz', default: 'now()' },
    } },
  },
  storage: { buckets: { avatars: { public: true } } },
})`)
    return
  }

  if (cmd === 'gen' && args[1] === 'types') {
    console.log('// Types generated by gddb gen types')
    console.log('export interface Database {')
    console.log('  tables: Record<string, { Row: Record<string, unknown> }>')
    console.log('}')
    return
  }

  console.log(`gd-db CLI

Usage:
  gddb keys generate       Generate a new master encryption key
  gddb init                 Print a starter gddb.config.ts
  gddb gen types            Print TypeScript types from schema

Author: thiskey (DevNova-ID — DreamToRealiityCreative)`)
}

main().catch(console.error)
