name = "gd-db"
main = "worker.js"
compatibility_date = "2026-09-19"
workers_dev = true
preview_urls = false

# Secrets (set via `wrangler secret put`):
#   GOOGLE_CLIENT_ID
#   GOOGLE_CLIENT_SECRET
#   GOOGLE_REDIRECT_URI
